variables:
  - group: azdo-backend-config
  - group: terraform-common-backend

pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

stages:
  - stage: Terraform_CI
    displayName: "Terraform CI"
    jobs:
      - job: terraform_validate_acr
        displayName: "Terraform Validate ACR"
        steps:
          - template: templates/terraform-env-init.yml
            parameters:
              Location: eu
              Section: acr
      - job: terraform_validate_aci
        displayName: "Terraform Validate ACI"
        steps:
          - template: templates/terraform-env-init.yml
            parameters:
              Location: eu
              Section: aci
  - stage: Terraform_CD_ACR
    displayName: "Terraform CD ACR"
    jobs:
      - template: templates/terraform-env-apply.yml
        parameters:
          Location: eu
          Section: acr
          Environment: prod
          Email: "emmanuel.legris@innocap.com"
  - stage: Docker
    displayName: "Docker Build"
    jobs:
      - template: templates/docker-build.yml
        parameters:
          Location: eu
          Section: acr
  - stage: Terraform_CD_ACI
    displayName: 'Terraform CD ACI'
    jobs:
      - template: templates/terraform-env-apply.yml
        parameters:
          Location: eu
          Section: aci
          Environment: prod
          Email: "emmanuel.legris@innocap.com"
          preTerraformTask:
            - task: replacetokens@3
              displayName: Replace Tokens
              inputs:
                rootDirectory: $(Build.SourcesDirectory)/deployments/eu
                targetFiles: 'prod-aci.tfvars'
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                enableTelemetry: false

