variables:
  - group: azdo-backend-config
  - group: terraform
  - group: security-cicd-scan

pool:
  vmImage: ubuntu-latest

schedules:
- cron: "0 1 * * 6"
  displayName: Weekly Saturday
  always: true
  branches:
    include:
    - main

trigger: none
pr: none

stages:
  - stage: Run_Security_Scanners
    displayName: Run Security Scanners
    jobs:
    - job:
      steps:
      - task: BoostSecurityScan@1
        inputs:
          apiToken: $(bsec_app_key)
          registryModule: boostsecurityio/native-scanner
  - stage: Docker
    displayName: "Docker Build"
    jobs:
      - template: templates/docker-build.yml
        parameters:
          Location: cu
          Section: acr
      - template: templates/docker-build.yml
        parameters:
          Location: eu
          Section: acr
      - template: templates/docker-build.yml
        parameters:
          Location: ci
          Section: acr
  - stage: Containers
    displayName: "Restart Containers"
    jobs:
      - template: templates/docker-restart.yml
  - stage: Cleanup
    displayName: "ACR Cleanup"
    jobs:
      - template: templates/docker-cleanup.yml
        parameters:
          Location: cu
          Section: acr
      - template: templates/docker-cleanup.yml
        parameters:
          Location: eu
          Section: acr
      - template: templates/docker-cleanup.yml
        parameters:
          Location: ci
          Section: acr

          
  