parameters:
  - name: ARM_SUBSCRIPTION_ID
  - name: ARM_CLIENT_ID
  - name: ARM_CLIENT_SECRET
  - name: ARM_TENANT_ID
  - name: AZURE_DEVOPS_EXT_PAT
  - name: AZP_URL

jobs:
  - job: ACI_Restart
    displayName: "ACI Restart"
    steps:
      - pwsh: |
          ./Restart-AzdoAgents.ps1 `
           -appId ${{ parameters.ARM_CLIENT_ID }} `
           -appSecret ${{ parameters.ARM_CLIENT_SECRET }} `
           -subscriptionId ${{ parameters.ARM_SUBSCRIPTION_ID }} `
           -tenant ${{ parameters.ARM_TENANT_ID }} `
           -azdoUrl ${{ parameters.AZP_URL }} `
           -azdoToken ${{ parameters.AZURE_DEVOPS_EXT_PAT }}
        displayName: "Restart ACI Containers"
        workingDirectory: $(Build.SourcesDirectory)/scripts
