parameters:
- name: Location
- name: Section
- name: Platform

jobs:
- job: Docker_Build
  displayName: 'Docker Build'
  steps:
    - template: terraform-env-init.yml
      parameters:
        Location: ${{ parameters.Location }}
        Section: ${{ parameters.Section }}
    - bash: |
        export ACR_NAME=$(cd ../../terraform-${{ parameters.Section }} && terraform output -json acr | jq -r . | jq ".ado.container_registry_name")
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
        az acr build --subscription $ARM_SUBSCRIPTION_ID --registry $ACR_NAME -t ${{ parameters.Platform }}agent:$(Build.BuildNumber) -t ${{ parameters.Platform }}agent:latest --timeout 7200 --platform ${{ parameters.Platform }} .
      displayName: 'Build Image'
      condition: eq('${{ parameters.Platform }}', 'linux')
      workingDirectory: $(Build.SourcesDirectory)/dockeragent/${{ parameters.Platform }}
      env:
        ARM_SUBSCRIPTION_ID: $(arm-subscription-id)
        ARM_CLIENT_ID:       $(arm-client-id)
        ARM_CLIENT_SECRET:   $(arm-client-secret)
        ARM_TENANT_ID:       $(tf-arm-tenant-id)
 